### ISSUE TITLE
KeyError: 'sources'

### ISSUE THREAD

**Issue by awoehrl** [z3z1ma/dbt-osmosis#115]
Hi!

I'm regularly seeing the following error, when trying to run dbt-osmosis. I'm not quite sure, but I think this happens, when I change the folder structure of my models, after I already generated yaml files. When I run dbt-osmosis again, I will see the error from time to time:

```
Traceback (most recent call last):
  File "/home/projects/.envs/dbt_env/bin/dbt-osmosis", line 8, in <module>
    sys.exit(cli())
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/dbt_osmosis/main.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/dbt_osmosis/main.py", line 216, in refactor
    if runner.commit_project_restructure_to_disk():
  File "/home/projects/.envs/dbt_env/lib/python3.10/site-packages/dbt_osmosis/core/osmosis.py", line 681, in commit_project_restructure_to_disk
    if structure.output["sources"]:
KeyError: 'sources'
```

**Comment by ArtemCLime** [comment]
@awoehrl Hey! I also faced with this error - it happens usually when `dbt-osmosis` faces with duplicated model. 
Your `dbt-osmosis` configuration sets a specific folder/files structure. When you generate YAML files, it places them according to your configuration path in your `dbt_project.yml`. If you change folder structure and run osmosis again - it will probably output in such an error - when trying to create a doc that already exists, but in a different location.
When you change the file structure of you models, remember to:
- check if your current `dbt-osmosis` configuration need to be changed according to it
- delete or move previously created YAML files to the configured location (because osmosis will not delete or move anything, it can only create new files or write to them)

To resolve this error try to look into the model file at which exception appeared and check if there are any duplicated YAML model exists already for it.
