### ISSUE TITLE
AttributeError: module 'dbt.config.profile' has no attribute 'DEFAULT_PROFILES_DIR'

### ISSUE THREAD

**Issue by prgx-aeveri01** [z3z1ma/dbt-osmosis#122]
Hi all,

I can't execute any of osmosis' function as I keep hitting this error:

`Traceback (most recent call last):
  File "/home/ail_aeveri01/git/cdm-sob-python/.venv/bin/dbt-osmosis", line 5, in <module>
    from dbt_osmosis.main import cli
  File "/home/ail_aeveri01/git/cdm-sob-python/.venv/lib/python3.7/site-packages/dbt_osmosis/main.py", line 162, in <module>
    DEFAULT_PROFILES_DIR = dbt.config.profile.DEFAULT_PROFILES_DIR
AttributeError: module 'dbt.config.profile' has no attribute 'DEFAULT_PROFILES_DIR'`

**Comment by prgx-aeveri01** [comment]
I'm running dbt trino 1.5.1 which is running dbt 1.5.9

**Comment by z3z1ma** [comment]
this should be resolved for some time, but definitely on latest
