### ISSUE TITLE
Add support for dbt 1.8.0

### ISSUE THREAD

**Issue by FrankTub** [z3z1ma/dbt-osmosis#148]
We tried to upgrade our environment to dbt 1.8.0 in combination with dbt-osmosis `v0.12.10`, but this results in an error. For example when running `dbt-osmosis --version` results in:

```shell
Traceback (most recent call last):
  File "/Users/frank.tubbing/source/repos/data-warehouse-etl-dbt/venv/bin/dbt-osmosis", line 5, in <module>
    from dbt_osmosis.main import cli
  File "/Users/frank.tubbing/source/repos/data-warehouse-etl-dbt/venv/lib/python3.12/site-packages/dbt_osmosis/main.py", line 14, in <module>
    from dbt_osmosis.core.diff import diff_and_print_to_console
  File "/Users/frank.tubbing/source/repos/data-warehouse-etl-dbt/venv/lib/python3.12/site-packages/dbt_osmosis/core/diff.py", line 10, in <module>
    from dbt_osmosis.vendored.dbt_core_interface.project import DbtProject
  File "/Users/frank.tubbing/source/repos/data-warehouse-etl-dbt/venv/lib/python3.12/site-packages/dbt_osmosis/vendored/dbt_core_interface/__init__.py", line 2, in <module>
    from .project import *  # noqa: F401, F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frank.tubbing/source/repos/data-warehouse-etl-dbt/venv/lib/python3.12/site-packages/dbt_osmosis/vendored/dbt_core_interface/project.py", line 88, in <module>
    from dbt.clients.system import make_directory
ModuleNotFoundError: No module named 'dbt.clients.system'
```

Other type of commands like `dbt-osmosis yaml document` result in the same error.

**Comment by z3z1ma** [comment]
Fixed by #151 , will cut new release on pypi today.
