### ISSUE TITLE
Can't run `workbench` - No souch file or directory: `streamlit` 

### ISSUE THREAD

**Issue by Nic3Guy** [z3z1ma/dbt-osmosis#15]
Hi, 
I installed the `dbt-osmosis` and tried to execute the `dbt-osmosis workbench` command
but I get error that `No such file or directory: 'streamlit'`

here is the full error msg: 
```➜  dbt git:(master) dbt-osmosis workbench
INFO     🌊 Executing dbt-osmosis                                                            main.py:390
                                                                                                        
Traceback (most recent call last):
  File "/Users/galpolak/Library/Python/3.9/bin/dbt-osmosis", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/galpolak/Library/Python/3.9/lib/python/site-packages/dbt_osmosis/main.py", line 414, in workbench
    subprocess.run(
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'streamlit'
```

**Comment by z3z1ma** [comment]
@Nic3Guy 

I need to update the documentation but I have moved the workbench to an optional dependency because its a heavier dependency and community usage in the `dbt-osmosis server` (open source dbt-server) is increasing significantly. 
Use `pip install 'dbt-osmosis[workbench]'`

I'll leave this issue open until II update the docs.

**Comment by Nic3Guy** [comment]
@z3z1ma Thx, this solved the issue.
