### ISSUE TITLE
[bug] dbt-osmosis breaking upon upgrading to dbt v1.8

### ISSUE THREAD

**Issue by brandonpeebles** [z3z1ma/dbt-osmosis#153]
I just tried upgrading to dbt v1.8.1 and it's causing dbt-osmosis to break. I know dbt-osmosis recently added support for 1.8 so I'm not sure of the issue here. I tried removing and reinstalling my virtual environment (using Poetry) but the same problem persists. If I downgrade to v1.7.x then it works again.
```
dbt-osmosis --version
Traceback (most recent call last):
  File "/home/vscode/workspaces/analytics-platform/.venv/bin/dbt-osmosis", line 5, in <module>
    from dbt_osmosis.main import cli
  File "/home/vscode/workspaces/analytics-platform/.venv/lib/python3.10/site-packages/dbt_osmosis/main.py", line 14, in <module>
    from dbt_osmosis.core.diff import diff_and_print_to_console
  File "/home/vscode/workspaces/analytics-platform/.venv/lib/python3.10/site-packages/dbt_osmosis/core/diff.py", line 10, in <module>
    from dbt_osmosis.vendored.dbt_core_interface.project import DbtProject
  File "/home/vscode/workspaces/analytics-platform/.venv/lib/python3.10/site-packages/dbt_osmosis/vendored/dbt_core_interface/__init__.py", line 2, in <module>
    from .project import *  # noqa: F401, F403
  File "/home/vscode/workspaces/analytics-platform/.venv/lib/python3.10/site-packages/dbt_osmosis/vendored/dbt_core_interface/project.py", line 88, in <module>
    from dbt.clients.system import make_directory
ModuleNotFoundError: No module named 'dbt.clients.system'
```

These are some of the related installs I have:
```
dbt-adapters==1.2.1
dbt-common==1.1.0
dbt-core==1.8.1
dbt-extractor==0.5.1
dbt-osmosis==0.12.10
dbt-snowflake==1.8.2
```

**Comment by syou6162** [comment]
https://github.com/z3z1ma/dbt-osmosis/pull/149 is dbt 1.8 compliant, but the reason it doesn't work on your end is that it is not yet included in the latest release (v0.12.10 was released 3 weeks ago, but dbt-osmosis's dbt 1.8 support was merge last week).

@z3z1ma Could you please create a new release?

**Comment by brandonpeebles** [comment]
@z3z1ma any chance we could create a new release here? Looking to upgrade my team's infra to dbt 1.8 but want to keep being able to use this tool 🙃

**Comment by z3z1ma** [comment]
Completed in 0.13.0
