### ISSUE TITLE
dbt.contracts.graph.parsed.ColumnInfo is move to dbt.contracts.graph.nodes.ColumnInfo from dbt 1.4

### ISSUE THREAD

**Issue by shin1103** [z3z1ma/dbt-osmosis#46]
Hi,
I tried to use dbt-osmosis with dbt 1.4 and got the following error.
```
hashiba@:~/work/dbt/jaffle_shop$ dbt-osmosis run --project-dir ~/work/dbt/jaffle_shop/ --target prod
Traceback (most recent call last):
  File "/Users/hashiba/.pyenv/versions/3.9.6/bin/dbt-osmosis", line 5, in <module>
    from dbt_osmosis.main import cli
  File "/Users/hashiba/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dbt_osmosis/main.py", line 15, in <module>
    from dbt_osmosis.core.diff import diff_and_print_to_console
  File "/Users/hashiba/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dbt_osmosis/core/diff.py", line 10, in <module>
    from dbt_osmosis.core.osmosis import DbtProject
  File "/Users/hashiba/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dbt_osmosis/core/osmosis.py", line 49, in <module>
    from dbt.contracts.graph.parsed import ColumnInfo
ModuleNotFoundError: No module named 'dbt.contracts.graph.parsed'
```

It's because, dbt.contracts.graph.parsed.ColumnInfo is move to dbt.contracts.graph.nodes.ColumnInfo from dbt 1.4.

I hope the next version will support this.

**Comment by shin1103** [comment]
Sorry, This issue is same as #37
